version: "2"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

## Ferramenta para gerenciamento de banco de dados.
  redis-commandr-interface:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: redis

##networks:
##  net:
##  driver: bridge