springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packagesToScan: br.com.blueproject.transactionbff.api

spring:
  redis:
    port: 6379
    host: localhost
    timeout: 5000 # default value is 60000 [ 60 segundos. ]

server:
  port: 8082

limites:
  url: http://localhost:8080