server:
  http2:
    enabled: true
  port: 8443 # Porta comum para acesso HTTPS.
  ssl:
    enabled: true
    protocol: TLSv1.3
    key-store-type: PKCS12
    key-store: classpath:keystore.jks
    key-store-password: changeit
    trust-store-password: changeit
    trust-store: classpath:cacerts.jks

spring:
#  main:
#    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.coffeeandit.com.br/auth/realms/master

  config:
    import: optional:configserver:http://localhost:8888/ # Origem de referência de propriedades para o sistema distribuído.

  application:
    name: transaction-bff

  kafka:
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: ${spring.application.name}
    bootstrap-servers: localhost:9092
    properties:
      spring:
        json:
          trusted:
            packages: br.com.blueproject.*

  redis:
    port: 6379
    host: localhost
    timeout: 5000 # default value is 60000 [ 60 segundos. ]

app:
  topic: transaction


management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true



limites:
  url: http://localhost:8086

transaction:
  url: http://localhost:8080


transacoes:
  events: "transferencias"
  duration: "3"


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packagesToScan: br.com.blueproject.transactionbff.api