spring:
  config:
    import: optional:configserver:http://localhost:8888/ # Origem de referência de propriedades para o sistema distribuído.

  application:
    name: transaction-bff

  kafka:
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: ${spring.application.name}
    properties:
      spring:
        json:
          trusted:
            packages: br.com.blueproject.*


app:
  topic: transaction

server:
  port: 8082



springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packagesToScan: br.com.blueproject.transactionbff.api