spring:
  application:
    name: transaction-bff

  kafka:
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: ${spring.application.name}
    bootstrap-servers: localhost:9092
    properties:
      spring:
        json:
          trusted:
            packages: br.com.blueproject.*


  redis:
    port: 6379
    host: localhost
    timeout: 5000 # default value is 60000 [ 60 segundos. ]

app:
  topic: transaction

server:
  port: 8082

limites:
  url: http://localhost:8080



springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packagesToScan: br.com.blueproject.transactionbff.api